# This workflow will build and deploy a React app to Azure Static Web Apps
# For more information: https://aka.ms/swaworkflow

name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
      - name: Install dependencies
        run: npm install
        working-directory: ./ContosoTraders.Ui.Website.V2.Raw/ContosoTraders.Ui.Website.V2
      - name: Build
        run: npm run build
        working-directory: ./ContosoTraders.Ui.Website.V2.Raw/ContosoTraders.Ui.Website.V2
      - name: Deploy to Azure Static Web Apps
        id: swa-deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for GitHub integrations (i.e. PR comments)
          action: 'upload'
          app_location: './ContosoTraders.Ui.Website.V2.Raw/ContosoTraders.Ui.Website.V2' # App source code path
          output_location: 'build' # Built app content directory
        env:
          skip_deploy_on_missing_secrets: true
